apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    app: proxy-service
spec:
  type: ClusterIP  # Внутренний IP в кластере
  ports:
  - port: 8000      # Порт Service
    targetPort: 8000 # Порт контейнера
    protocol: TCP
    name: http
  selector:
    app: proxy-service  # Связывает Service с pod'ами по label
